### ISSUE TITLE
Heads-up: UB due to misuse of mem::uninitialized will soon lead to panic

### ISSUE THREAD

**Issue by RalfJung** [emilk/drop-merge-sort#2]
[Here](https://github.com/emilk/drop-merge-sort/blob/0c677885ed1a429d9be3ad62e725fc7c1d074bdc/src/dmsort.rs#L219), this crate causes UB by ["Producing an invalid value"](https://doc.rust-lang.org/reference/behavior-considered-undefined.html). Concretely, it creates an arbitrary  `T` with `mem::uninitialized()`. In the near future the call to `mem::uninitialized()` [will panic to avoid UB](https://github.com/rust-lang/rust/pull/66059), and [our crater run](https://github.com/rust-lang/rust/pull/66059#issuecomment-575164263) determined that this crate will be affected.

`mem::uninitialized()` is deprecated since Rust 1.39. The intended replacement is [`MaybeUninit`](https://doc.rust-lang.org/core/mem/union.MaybeUninit.html), which tracks the possibility of uninitialized values at the type level to make sure the compiler does not make any false assumptions.

**Comment by calixteman** [comment]
@RalfJung, any chance to have a fix here ?

**Comment by RalfJung** [comment]
I'm not familiar with this library I am afraid. I am working on rustc and the library just showed up when we did our regression testing for this change.

Cc https://github.com/rust-lang/rust/issues/66151

**Comment by emilk** [comment]
@ilaril made a beautiful fix, and I have released a `1.0.1`
